version: '2'

services:

    couchdb2:
      container_name: couchdb2
      image: hyperledger/fabric-couchdb:latest
      environment:
        - COUCHDB_USER=admin
        - COUCHDB_PASSWORD=000000
      ports:
        - "7984:5984"
    peer0.org2.iot.com:
      container_name: peer0.org2.iot.com
      image: hyperledger/fabric-peer:latest
      environment:
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=000000
        
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=iot_default
        - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
        
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_PROFILE_ENABLED=true
        - CORE_PEER_ID=peer0.org2.iot.com
        - CORE_PEER_ADDRESS=peer0.org2.iot.com:7051
        - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.iot.com:7051
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.iot.com:7051
        - CORE_PEER_LOCALMSPID=Org2MSP
                
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
        
      volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org2.iot.com/peers/peer0.org2.iot.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org2.iot.com/peers/peer0.org2.iot.com/tls:/etc/hyperledger/fabric/tls
        #- peer0.org2.iot.com:/var/hyperledger/production

      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: peer node start
      networks:
        default:
          aliases:
            - iot
      ports:
        - 9051:7051
        - 9053:7053
      #extra_hosts:
        #- "orderer.test.com:192.168.43.76"
      depends_on:
        - couchdb2
